export const WS_CONNECTION_BEGIN = 'WS_CONNECTION_BEGIN';
export const WS_CONNECTION_SUCCESS = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_CLOSE_CLEAN = 'WS_CONNECTION_CLOSE_CLEAN';
export const WS_CONNECTION_CLOSE_ERROR = 'WS_CONNECTION_CLOSE_ERROR';
export const WS_GET_MESSAGE = 'WS_GET_MESSAGE';
export const WS_GET_ERROR = 'WS_GET_ERROR';
export const WS_SEND_MESSAGE = 'WS_SEND_MESSAGE';

export const SEND_COMMAND = 'SEND_COMMAND';
export const SEND_CHAT_MESSAGE = 'SEND_CHAT_MESSAGE';
